exclude = [
    "**/__pycache__",
    "**/tests",
    "build",
    "dist",
    "docs",
    "tach.egg-info",
]
source_roots = [
    "python",
]
exact = true
forbid_circular_dependencies = true
use_regex_matching = false

[[modules]]
path = "tach"
depends_on = []

[[modules]]
path = "tach.__main__"
depends_on = [
    { path = "tach.start" },
]

[[modules]]
path = "tach.cache"
depends_on = [
    { path = "tach" },
    { path = "tach.filesystem" },
]

[[modules]]
path = "tach.check_external"
depends_on = [
    { path = "tach.extension" },
]

[[modules]]
path = "tach.cli"
depends_on = [
    { path = "tach" },
    { path = "tach.cache" },
    { path = "tach.check_external" },
    { path = "tach.extension" },
    { path = "tach.filesystem" },
    { path = "tach.icons" },
    { path = "tach.logging" },
    { path = "tach.mod" },
    { path = "tach.modularity" },
    { path = "tach.parsing" },
    { path = "tach.report" },
    { path = "tach.show" },
    { path = "tach.sync" },
    { path = "tach.test" },
]

[[modules]]
path = "tach.colors"
depends_on = []
utility = true

[[modules]]
path = "tach.constants"
depends_on = []
utility = true

[[modules]]
path = "tach.errors"
depends_on = []
utility = true

[[modules]]
path = "tach.extension"
depends_on = []

[[modules]]
path = "tach.filesystem"
depends_on = [
    { path = "tach.hooks" },
]

[[modules]]
path = "tach.filesystem.git_ops"
depends_on = []

[[modules]]
path = "tach.hooks"
depends_on = []

[[modules]]
path = "tach.icons"
depends_on = []

[[modules]]
path = "tach.interactive"
depends_on = [
    { path = "tach.filesystem" },
]

[[modules]]
path = "tach.logging"
depends_on = [
    { path = "tach" },
    { path = "tach.cache" },
    { path = "tach.parsing" },
]

[[modules]]
path = "tach.mod"
depends_on = [
    { path = "tach.filesystem" },
    { path = "tach.interactive" },
    { path = "tach.parsing" },
]

[[modules]]
path = "tach.modularity"
depends_on = [
    { path = "tach.extension" },
    { path = "tach.filesystem" },
    { path = "tach.filesystem.git_ops" },
    { path = "tach.parsing" },
]

[[modules]]
path = "tach.parsing"
depends_on = [
    { path = "tach.extension" },
    { path = "tach.filesystem" },
]

[[modules]]
path = "tach.pytest_plugin"
depends_on = [
    { path = "tach.extension" },
    { path = "tach.filesystem" },
    { path = "tach.filesystem.git_ops" },
    { path = "tach.parsing" },
]

[[modules]]
path = "tach.report"
depends_on = [
    { path = "tach.extension" },
    { path = "tach.filesystem" },
]

[[modules]]
path = "tach.show"
depends_on = [
    { path = "tach.extension" },
    { path = "tach.filesystem" },
]

[[modules]]
path = "tach.start"
depends_on = [
    { path = "tach.cli" },
]

[[modules]]
path = "tach.sync"
depends_on = [
    { path = "tach.extension" },
    { path = "tach.filesystem" },
]

[[modules]]
path = "tach.test"
depends_on = []

[[modules]]
path = "tach.utils"
depends_on = []
utility = true

[[interfaces]]
expose = [
    "export_report",
    "upload_report_to_gauge",
]
from = [
    "tach.modularity",
]
serializable = true

[[interfaces]]
expose = [
    "__version__",
]
from = [
    "tach",
]
serializable = true

[[interfaces]]
expose = [
    "main",
]
from = [
    "tach.cli",
]
serializable = true

[[interfaces]]
expose = [
    "BCOLORS",
]
from = [
    "tach.colors",
]
serializable = true

[[interfaces]]
expose = [
    "PACKAGE_NAME",
    "TOOL_NAME",
    "CONFIG_FILE_NAME",
    "PACKAGE_FILE_NAME",
    "ROOT_MODULE_SENTINEL_TAG",
    "DEFAULT_EXCLUDE_PATHS",
]
from = [
    "tach.constants",
]
serializable = true

[[interfaces]]
expose = [
    "get_changed_files",
    "get_current_branch_info",
]
from = [
    "tach.filesystem.git_ops",
]
serializable = true

[[interfaces]]
expose = [
    "build_pre_commit_hook_content",
]
from = [
    "tach.hooks",
]
serializable = true

[[interfaces]]
expose = [
    "get_selected_modules_interactive",
    "InteractiveModuleConfiguration",
]
from = [
    "tach.interactive",
]
serializable = true

[[interfaces]]
expose = [
    "logger",
    "LogDataModel",
]
from = [
    "tach.logging",
]
serializable = true

[[interfaces]]
expose = [
    "mod_edit_interactive",
]
from = [
    "tach.mod",
]
serializable = true

[[interfaces]]
expose = [
    "parse_project_config",
    "dump_project_config_to_toml",
    "extend_and_validate",
]
from = [
    "tach.parsing",
]
serializable = true

[[interfaces]]
expose = [
    "report",
    "external_dependency_report",
]
from = [
    "tach.report",
]
serializable = true

[[interfaces]]
expose = [
    "generate_show_url",
    "generate_module_graph_dot_file",
    "generate_module_graph_mermaid",
]
from = [
    "tach.show",
]
serializable = true

[[interfaces]]
expose = [
    "start",
]
from = [
    "tach.start",
]
serializable = true

[[interfaces]]
expose = [
    "sync_project",
]
from = [
    "tach.sync",
]
serializable = true

[[interfaces]]
expose = [
    "run_affected_tests",
]
from = [
    "tach.test",
]
serializable = true

[cache]
file_dependencies = [
    "python/tests/**",
    "src/*.rs",
]

[external]
exclude = [
    "pytest",
    "pydot",
    "eval_type_backport",
]

[rules]
unused_ignore_directives = "error"
require_ignore_directive_reasons = "error"
